// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo_ooR4yLWHAngN930UimrMmigt_ncfTw',
    appId: '1:589138236143:web:7b28b6972b5dfa7a03411a',
    messagingSenderId: '589138236143',
    projectId: 'sonsom-financial-tracker',
    authDomain: 'sonsom-financial-tracker.firebaseapp.com',
    storageBucket: 'sonsom-financial-tracker.firebasestorage.app',
    measurementId: 'G-ZDYYGZXB3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPn1d5zk1xdMsGx7CbcusW2WaVKSTz8Q4',
    appId: '1:589138236143:android:bc0a8a92be2d408103411a',
    messagingSenderId: '589138236143',
    projectId: 'sonsom-financial-tracker',
    storageBucket: 'sonsom-financial-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrwWrUnhJkQ4J1afNtQiCATDXxj9gXzOs',
    appId: '1:589138236143:ios:58145bd284dae63003411a',
    messagingSenderId: '589138236143',
    projectId: 'sonsom-financial-tracker',
    storageBucket: 'sonsom-financial-tracker.firebasestorage.app',
    iosBundleId: 'come.somsom.saving.kh.sonsomFinancialTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrwWrUnhJkQ4J1afNtQiCATDXxj9gXzOs',
    appId: '1:589138236143:ios:58145bd284dae63003411a',
    messagingSenderId: '589138236143',
    projectId: 'sonsom-financial-tracker',
    storageBucket: 'sonsom-financial-tracker.firebasestorage.app',
    iosBundleId: 'come.somsom.saving.kh.sonsomFinancialTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo_ooR4yLWHAngN930UimrMmigt_ncfTw',
    appId: '1:589138236143:web:83d90f315ca121fc03411a',
    messagingSenderId: '589138236143',
    projectId: 'sonsom-financial-tracker',
    authDomain: 'sonsom-financial-tracker.firebaseapp.com',
    storageBucket: 'sonsom-financial-tracker.firebasestorage.app',
    measurementId: 'G-G3S3552Y3F',
  );
}
